name: wgs-processing
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - pip=20.1.1
  - fastqc=0.11.9
  - multiqc=1.9
  - fastp=0.20.0
  - megahit=1.2.9
  - samtools=1.10
  - bwa=0.7.17
  - quast=5.0.2
  - minimap2=2.17
  - spades=3.14.0
  - prokka=1.14.6
  - virsorter=1.0.6
  - trimmomatic=0.38
  - bowtie2=2.4.1
  - kraken2=2.0.9beta
  - prodigal=2.6.3
  
