name: wgs-processing
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip=20.1.1
  - fastqc=0.11.9
  - multiqc=1.9
  - fastp=0.20.0
  - megahit=1.2.9
  - samtools=1.10
  - bwa=0.7.17
  - quast=5.0.2
  - minimap2=2.17
  - spades=3.14.0
  - metabat2=2.15
  - prokka=1.14.6
  - virsorter=2.0.beta
  - trimmomatic=0.38
  - kraken2=2.0.9beta
  - prodigal=2.6.3
  - pyyaml=5.1.0
  - pandas=1.1
  - h5py=2.10.0
  - bioawk=1.0
  - biopython=1.77
  - scikit-learn=0.23.1
  - pytorch=1.6.0
  - python-igraph=0.8.2
  - leidenalg=0.8.1
  - tqdm==4.48.0
  - pip:
      - coconet-binning==0.52
  
